[tool.poetry]
name = "omicidx-gh-etl"
version = "0.1.0"
description = ""
authors = ["Sean Davis <seandavi@gmail.com>"]
license = "MIT"
packages = [{include = "omicidx_etl"}]

[tool.poetry.dependencies]
python = "^3.9"
omicidx = "^1.12.0"
universal-pathlib = "^0.2.2"
rich = "^13.7.1"
s3fs = "^2023.0.0"
orjson = "^3.10.3"
pubmed-parser = {git = "https://github.com/seandavi/pubmed_parser"}
gcsfs = "^2023.0.0"
pydantic-settings = "^2.3.3"
clickhouse-connect = "^0.7.12"
google-cloud-bigquery = "^3.24.0"
prefect = "3.0.0rc9"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
