[tool.poetry]
name = "omicidx-gh-etl"
version = "0.1.0"
description = ""
authors = ["Sean Davis <seandavi@gmail.com>"]
license = "MIT"
packages = [{include = "omicidx_etl"}]

[tool.poetry.dependencies]
python = "^3.9"
omicidx = "^1.11.3"
universal-pathlib = "^0.2.2"
rich = "^13.7.1"
s3fs = "^2024.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
