version: 2

models:
  - name: sra_metadata
    description: |
      **Production-ready SRA metadata view**

      This is the primary export view that combines:
      - Study metadata and descriptions
      - Experiment details and sequencing parameters
      - Sample information and organism data
      - Aggregate statistics

      **Use cases:**
      - Export to parquet for public distribution
      - API/query endpoint for SRA metadata
      - Analytics and reporting

      **Refresh frequency:** Updated when staging models are refreshed

      **Data quality:** Only includes records with complete metadata
    materialized: view
    depends_on:
      - staging.stg_sra_studies
      - staging.stg_sra_experiments
      - raw.sra_samples
    tags:
      - mart
      - sra
      - production
      - export-ready
    columns:
      - name: study_accession
        description: SRA study accession (primary identifier)
      - name: study_title
        description: Human-readable study title
      - name: study_type
        description: Study type classification
      - name: abstract
        description: Study abstract/description
      - name: publish_date
        description: Study publication date
      - name: BioProject
        description: Linked BioProject accession
      - name: study_geo
        description: Linked GEO series (GSE)
      - name: experiment_accession
        description: SRA experiment accession
      - name: platform
        description: Sequencing platform used
      - name: instrument_model
        description: Specific sequencing instrument
      - name: library_strategy
        description: Library preparation strategy (RNA-Seq, WGS, etc.)
      - name: library_source
        description: Source material for library
      - name: library_selection
        description: Library selection method
      - name: library_layout
        description: Single-end or paired-end sequencing
      - name: sample_accession
        description: SRA sample accession
      - name: organism
        description: Source organism scientific name
      - name: taxon_id
        description: NCBI taxonomy identifier
      - name: BioSample
        description: Linked BioSample accession
      - name: experiment_count
        description: Number of experiments in this study
      - name: has_complete_metadata
        description: Quality flag indicating metadata completeness
      - name: study_loaded_at
        description: Timestamp of last data refresh
