name: CI
on: [pull_request, workflow_dispatch]

jobs:
  ci:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'my-project'
          workload_identity_provider: 'projects/492900567997/locations/global/workloadIdentityPools/github/providers/my-repo'
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python -
      - name: Install dependencies
        run: poetry install
      - name: run etl
        run: poetry run python -m omicidx_etl.etl.pubmed
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FSSPEC_S3_ENDPOINT_URL: ${{ secrets.FSSPEC_S3_ENDPOINT_URL }}