name: ETL for geo
on: 
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 1 * * *'

jobs:
  call-reusable-workflow:
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: ./.github/workflows/base_runner.yaml
    with:
      module_to_run: omicidx_etl.geo.etl
    secrets: inherit


