name: ETL for NCBI SRA
on: 
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 5 * * *'

jobs:
  call-reusable-workflow:
    permissions:
      contents: 'read'
      id-token: 'write'
    uses: ./.github/workflows/base_runner.yaml
    with:
      module_to_run: 'omicidx_etl.sra.etl'
    secrets: inherit
