name: ETL for biosample
on: 
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 1 * * *'

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/base_runner.yaml
    with:
      module_to_run: 'omicidx_etl.biosample.etl'
    secrets: inherit